version: '3'
services:

  eureka-service:
    image: sbm/eureka-service:v1
    ports:
      - "8302:8302"

  routing-service:
    image: sbm/routing-service:v1
    ports:
      - "8303:8303"
    environment:
      STOCK_SERVICE_HOST: "stock-service"
      DB2_SERVICE_HOST: "db2-service"


  stock-service:
    image: sbm/stock-service:v1
    ports:
      - "8301:8301"
    environment:
        STOCK_SERVICE_HOST: "stock-service"
        EUREKA_SERVICE_HOST: "eureka-service"
        ALLOWED_CORS: "${FRONTEND_HOSTNAME}"
    depends_on:
      - "eureka-service"

  db2-service:
    image: sbm/db2-service:v1
    ports:
      - "8300:8300"
    environment:
      # DB_HOST: "mysql"
       DB_HOST: "mysql-service"
       DB2_SERVICE_HOST: "db2-service"
       EUREKA_SERVICE_HOST: "eureka-service"
       ALLOWED_CORS: "${FRONTEND_HOSTNAME}"
    depends_on:
      - "eureka-service"
      # - "mysql-service"

  # web:
  #   external_links:
  #     - mysql101



  mysql-service:
    image: mysql/mysql-server:5.6 
    depends_on:
      - "eureka-service"
    
    environment:
       MYSQL_ROOT_HOST: "%" 
       MYSQL_ROOT_PASSWORD: db-password
       MYSQL_DATABASE: db_example 

    command: --lower_case_table_names=1 --init-connect='GRANT CREATE USER ON *.* TO 'root'@'%';FLUSH PRIVILEGES;'
    ports:
      - "3306:3306" 
    volumes:
      - /tmp:/tmp
    