spring:
  application:
    name: stock-service

server:
  port: 8301

eureka:
  instance:
    hostname: ${STOCK_SERVICE_HOST:localhost}
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://${EUREKA_SERVICE_HOST:localhost}:8302/eureka/
#      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/